# .streamlit/config.toml
# Clean & Compatible for Streamlit Cloud

[server]
port = 8501
enableCORS = false
enableXsrfProtection = false
headless = true
maxUploadSize = 200
maxMessageSize = 200

[theme]
primaryColor = "#2E3192"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[browser]
gatherUsageStats = false
